<?php


/**
 * This class defines the structure of the 'aspectos_legales' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/17/10 19:39:08
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class AspectosLegalesTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.AspectosLegalesTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('aspectos_legales');
		$this->setPhpName('AspectosLegales');
		$this->setClassname('AspectosLegales');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('aspectos_legales_ale_id_seq');
		// columns
		$this->addPrimaryKey('ALE_ID', 'AleId', 'INTEGER', true, null, null);
		$this->addForeignKey('ALE_MIC_ID', 'AleMicId', 'INTEGER', 'microcuencas', 'MIC_ID', false, null, null);
		$this->addColumn('ALE_CUMPLE_PERISOS', 'AleCumplePerisos', 'BOOLEAN', false, null, null);
		$this->addColumn('ALE_ENTIDAD_EXIDIO_CONCESION', 'AleEntidadExidioConcesion', 'VARCHAR', false, 100, null);
		$this->addColumn('ALE_FECHA_EXPEDICION_CONCESION', 'AleFechaExpedicionConcesion', 'DATE', false, null, null);
		$this->addColumn('ALE_FECHA_VENCIMIENTO_CONCESION', 'AleFechaVencimientoConcesion', 'DATE', false, null, null);
		$this->addColumn('ALE_CAUDAL_ADJUDICADO_CONCESION', 'AleCaudalAdjudicadoConcesion', 'INTEGER', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Microcuencas', 'Microcuencas', RelationMap::MANY_TO_ONE, array('ale_mic_id' => 'mic_id', ), 'RESTRICT', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // AspectosLegalesTableMap
