<?php


/**
 * This class defines the structure of the 'comunidadserviciorecoleccion' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/28/10 13:25:11
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class ComunidadserviciorecoleccionTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.ComunidadserviciorecoleccionTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('comunidadserviciorecoleccion');
		$this->setPhpName('Comunidadserviciorecoleccion');
		$this->setClassname('Comunidadserviciorecoleccion');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('comunidadserviciorecoleccion_csr_id_seq');
		// columns
		$this->addPrimaryKey('CSR_ID', 'CsrId', 'INTEGER', true, null, null);
		$this->addForeignKey('CSR_SRSF_ID', 'CsrSrsfId', 'INTEGER', 'separacionresiduossolidosfuentesaseo', 'SRSF_ID', true, null, null);
		$this->addColumn('CSR_NOMBRE_COMUNIDAD', 'CsrNombreComunidad', 'VARCHAR', true, 200, null);
		$this->addColumn('CSR_NUMERO_VIVIENDAS_TOTALES', 'CsrNumeroViviendasTotales', 'INTEGER', false, null, null);
		$this->addColumn('CSR_NUMERO_VIVIENDAS_CON_SERVICIO', 'CsrNumeroViviendasConServicio', 'INTEGER', false, null, null);
		$this->addColumn('CSR_NUMERO_SUSCRIPTORES', 'CsrNumeroSuscriptores', 'INTEGER', false, null, null);
		$this->addColumn('CSR_CANTIDAD_PROM_RESIDUOS_MES', 'CsrCantidadPromResiduosMes', 'VARCHAR', false, 255, null);
		$this->addColumn('CSR_FECHA_PESAJE', 'CsrFechaPesaje', 'DATE', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Separacionresiduossolidosfuentesaseo', 'Separacionresiduossolidosfuentesaseo', RelationMap::MANY_TO_ONE, array('csr_srsf_id' => 'srsf_id', ), 'RESTRICT', 'RESTRICT');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // ComunidadserviciorecoleccionTableMap
