<?php


/**
 * This class defines the structure of the 'vinculacionalservicio' table.
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/26/10 20:32:57
 *
 *
 * This map class is used by Propel to do runtime db structure discovery.
 * For example, the createSelectSql() method checks the type of a given column used in an
 * ORDER BY clause to know whether it needs to apply SQL to make the ORDER BY case-insensitive
 * (i.e. if it's a text column type).
 *
 * @package    lib.model.map
 */
class VinculacionalservicioTableMap extends TableMap {

	/**
	 * The (dot-path) name of this class
	 */
	const CLASS_NAME = 'lib.model.map.VinculacionalservicioTableMap';

	/**
	 * Initialize the table attributes, columns and validators
	 * Relations are not initialized by this method since they are lazy loaded
	 *
	 * @return     void
	 * @throws     PropelException
	 */
	public function initialize()
	{
	  // attributes
		$this->setName('vinculacionalservicio');
		$this->setPhpName('Vinculacionalservicio');
		$this->setClassname('Vinculacionalservicio');
		$this->setPackage('lib.model');
		$this->setUseIdGenerator(true);
		$this->setPrimaryKeyMethodInfo('vinculacionalservicio_vas_id_seq');
		// columns
		$this->addPrimaryKey('VAS_ID', 'VasId', 'INTEGER', true, null, null);
		$this->addForeignKey('VAS_COM_ID', 'VasComId', 'INTEGER', 'comercial', 'COM_ID', true, null, null);
		$this->addColumn('VAS_SUSCRIPCION_CONTRATO', 'VasSuscripcionContrato', 'BOOLEAN', false, null, null);
		// validators
	} // initialize()

	/**
	 * Build the RelationMap objects for this table relationships
	 */
	public function buildRelations()
	{
    $this->addRelation('Comercial', 'Comercial', RelationMap::MANY_TO_ONE, array('vas_com_id' => 'com_id', ), 'RESTRICT', 'CASCADE');
	} // buildRelations()

	/**
	 * 
	 * Gets the list of behaviors registered for this table
	 * 
	 * @return array Associative array (name => parameters) of behaviors
	 */
	public function getBehaviors()
	{
		return array(
			'symfony' => array('form' => 'true', 'filter' => 'true', ),
			'symfony_behaviors' => array(),
		);
	} // getBehaviors()

} // VinculacionalservicioTableMap
