<?php

/**
 * Base class that represents a row from the 'periodoporprestadorservicio' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/17/10 19:39:18
 *
 * @package    lib.model.om
 */
abstract class BasePeriodoporprestadorservicio extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        PeriodoporprestadorservicioPeer
	 */
	protected static $peer;

	/**
	 * The value for the pps_pre_id field.
	 * @var        int
	 */
	protected $pps_pre_id;

	/**
	 * The value for the pps_ser_id field.
	 * @var        int
	 */
	protected $pps_ser_id;

	/**
	 * The value for the pps_anio field.
	 * @var        int
	 */
	protected $pps_anio;

	/**
	 * The value for the pps_presupuesto_aprobado field.
	 * @var        boolean
	 */
	protected $pps_presupuesto_aprobado;

	/**
	 * The value for the pps_suscriptores_pendientes_de_pago field.
	 * @var        string
	 */
	protected $pps_suscriptores_pendientes_de_pago;

	/**
	 * @var        Prestador
	 */
	protected $aPrestador;

	/**
	 * @var        Servicio
	 */
	protected $aServicio;

	/**
	 * @var        array Administrativafinanciera[] Collection to store aggregation of Administrativafinanciera objects.
	 */
	protected $collAdministrativafinancieras;

	/**
	 * @var        Criteria The criteria used to select the current contents of collAdministrativafinancieras.
	 */
	private $lastAdministrativafinancieraCriteria = null;

	/**
	 * @var        array Calidad[] Collection to store aggregation of Calidad objects.
	 */
	protected $collCalidads;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCalidads.
	 */
	private $lastCalidadCriteria = null;

	/**
	 * @var        array Cormecial[] Collection to store aggregation of Cormecial objects.
	 */
	protected $collCormecials;

	/**
	 * @var        Criteria The criteria used to select the current contents of collCormecials.
	 */
	private $lastCormecialCriteria = null;

	/**
	 * @var        array Microcuencas[] Collection to store aggregation of Microcuencas objects.
	 */
	protected $collMicrocuencass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collMicrocuencass.
	 */
	private $lastMicrocuencasCriteria = null;

	/**
	 * @var        array Tecnicooperativo[] Collection to store aggregation of Tecnicooperativo objects.
	 */
	protected $collTecnicooperativos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTecnicooperativos.
	 */
	private $lastTecnicooperativoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'PeriodoporprestadorservicioPeer';

	/**
	 * Get the [pps_pre_id] column value.
	 * 
	 * @return     int
	 */
	public function getPpsPreId()
	{
		return $this->pps_pre_id;
	}

	/**
	 * Get the [pps_ser_id] column value.
	 * 
	 * @return     int
	 */
	public function getPpsSerId()
	{
		return $this->pps_ser_id;
	}

	/**
	 * Get the [pps_anio] column value.
	 * 
	 * @return     int
	 */
	public function getPpsAnio()
	{
		return $this->pps_anio;
	}

	/**
	 * Get the [pps_presupuesto_aprobado] column value.
	 * 
	 * @return     boolean
	 */
	public function getPpsPresupuestoAprobado()
	{
		return $this->pps_presupuesto_aprobado;
	}

	/**
	 * Get the [pps_suscriptores_pendientes_de_pago] column value.
	 * 
	 * @return     string
	 */
	public function getPpsSuscriptoresPendientesDePago()
	{
		return $this->pps_suscriptores_pendientes_de_pago;
	}

	/**
	 * Set the value of [pps_pre_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Periodoporprestadorservicio The current object (for fluent API support)
	 */
	public function setPpsPreId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pps_pre_id !== $v) {
			$this->pps_pre_id = $v;
			$this->modifiedColumns[] = PeriodoporprestadorservicioPeer::PPS_PRE_ID;
		}

		if ($this->aPrestador !== null && $this->aPrestador->getPreId() !== $v) {
			$this->aPrestador = null;
		}

		return $this;
	} // setPpsPreId()

	/**
	 * Set the value of [pps_ser_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Periodoporprestadorservicio The current object (for fluent API support)
	 */
	public function setPpsSerId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pps_ser_id !== $v) {
			$this->pps_ser_id = $v;
			$this->modifiedColumns[] = PeriodoporprestadorservicioPeer::PPS_SER_ID;
		}

		if ($this->aServicio !== null && $this->aServicio->getSerId() !== $v) {
			$this->aServicio = null;
		}

		return $this;
	} // setPpsSerId()

	/**
	 * Set the value of [pps_anio] column.
	 * 
	 * @param      int $v new value
	 * @return     Periodoporprestadorservicio The current object (for fluent API support)
	 */
	public function setPpsAnio($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->pps_anio !== $v) {
			$this->pps_anio = $v;
			$this->modifiedColumns[] = PeriodoporprestadorservicioPeer::PPS_ANIO;
		}

		return $this;
	} // setPpsAnio()

	/**
	 * Set the value of [pps_presupuesto_aprobado] column.
	 * 
	 * @param      boolean $v new value
	 * @return     Periodoporprestadorservicio The current object (for fluent API support)
	 */
	public function setPpsPresupuestoAprobado($v)
	{
		if ($v !== null) {
			$v = (boolean) $v;
		}

		if ($this->pps_presupuesto_aprobado !== $v) {
			$this->pps_presupuesto_aprobado = $v;
			$this->modifiedColumns[] = PeriodoporprestadorservicioPeer::PPS_PRESUPUESTO_APROBADO;
		}

		return $this;
	} // setPpsPresupuestoAprobado()

	/**
	 * Set the value of [pps_suscriptores_pendientes_de_pago] column.
	 * 
	 * @param      string $v new value
	 * @return     Periodoporprestadorservicio The current object (for fluent API support)
	 */
	public function setPpsSuscriptoresPendientesDePago($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->pps_suscriptores_pendientes_de_pago !== $v) {
			$this->pps_suscriptores_pendientes_de_pago = $v;
			$this->modifiedColumns[] = PeriodoporprestadorservicioPeer::PPS_SUSCRIPTORES_PENDIENTES_DE_PAGO;
		}

		return $this;
	} // setPpsSuscriptoresPendientesDePago()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->pps_pre_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->pps_ser_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->pps_anio = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->pps_presupuesto_aprobado = ($row[$startcol + 3] !== null) ? (boolean) $row[$startcol + 3] : null;
			$this->pps_suscriptores_pendientes_de_pago = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 5; // 5 = PeriodoporprestadorservicioPeer::NUM_COLUMNS - PeriodoporprestadorservicioPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Periodoporprestadorservicio object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aPrestador !== null && $this->pps_pre_id !== $this->aPrestador->getPreId()) {
			$this->aPrestador = null;
		}
		if ($this->aServicio !== null && $this->pps_ser_id !== $this->aServicio->getSerId()) {
			$this->aServicio = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PeriodoporprestadorservicioPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = PeriodoporprestadorservicioPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aPrestador = null;
			$this->aServicio = null;
			$this->collAdministrativafinancieras = null;
			$this->lastAdministrativafinancieraCriteria = null;

			$this->collCalidads = null;
			$this->lastCalidadCriteria = null;

			$this->collCormecials = null;
			$this->lastCormecialCriteria = null;

			$this->collMicrocuencass = null;
			$this->lastMicrocuencasCriteria = null;

			$this->collTecnicooperativos = null;
			$this->lastTecnicooperativoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PeriodoporprestadorservicioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePeriodoporprestadorservicio:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				PeriodoporprestadorservicioPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePeriodoporprestadorservicio:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(PeriodoporprestadorservicioPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BasePeriodoporprestadorservicio:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BasePeriodoporprestadorservicio:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				PeriodoporprestadorservicioPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPrestador !== null) {
				if ($this->aPrestador->isModified() || $this->aPrestador->isNew()) {
					$affectedRows += $this->aPrestador->save($con);
				}
				$this->setPrestador($this->aPrestador);
			}

			if ($this->aServicio !== null) {
				if ($this->aServicio->isModified() || $this->aServicio->isNew()) {
					$affectedRows += $this->aServicio->save($con);
				}
				$this->setServicio($this->aServicio);
			}


			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = PeriodoporprestadorservicioPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setNew(false);
				} else {
					$affectedRows += PeriodoporprestadorservicioPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collAdministrativafinancieras !== null) {
				foreach ($this->collAdministrativafinancieras as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCalidads !== null) {
				foreach ($this->collCalidads as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collCormecials !== null) {
				foreach ($this->collCormecials as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collMicrocuencass !== null) {
				foreach ($this->collMicrocuencass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTecnicooperativos !== null) {
				foreach ($this->collTecnicooperativos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aPrestador !== null) {
				if (!$this->aPrestador->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aPrestador->getValidationFailures());
				}
			}

			if ($this->aServicio !== null) {
				if (!$this->aServicio->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aServicio->getValidationFailures());
				}
			}


			if (($retval = PeriodoporprestadorservicioPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collAdministrativafinancieras !== null) {
					foreach ($this->collAdministrativafinancieras as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCalidads !== null) {
					foreach ($this->collCalidads as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collCormecials !== null) {
					foreach ($this->collCormecials as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collMicrocuencass !== null) {
					foreach ($this->collMicrocuencass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTecnicooperativos !== null) {
					foreach ($this->collTecnicooperativos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PeriodoporprestadorservicioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getPpsPreId();
				break;
			case 1:
				return $this->getPpsSerId();
				break;
			case 2:
				return $this->getPpsAnio();
				break;
			case 3:
				return $this->getPpsPresupuestoAprobado();
				break;
			case 4:
				return $this->getPpsSuscriptoresPendientesDePago();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = PeriodoporprestadorservicioPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getPpsPreId(),
			$keys[1] => $this->getPpsSerId(),
			$keys[2] => $this->getPpsAnio(),
			$keys[3] => $this->getPpsPresupuestoAprobado(),
			$keys[4] => $this->getPpsSuscriptoresPendientesDePago(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = PeriodoporprestadorservicioPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setPpsPreId($value);
				break;
			case 1:
				$this->setPpsSerId($value);
				break;
			case 2:
				$this->setPpsAnio($value);
				break;
			case 3:
				$this->setPpsPresupuestoAprobado($value);
				break;
			case 4:
				$this->setPpsSuscriptoresPendientesDePago($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = PeriodoporprestadorservicioPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setPpsPreId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setPpsSerId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setPpsAnio($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setPpsPresupuestoAprobado($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setPpsSuscriptoresPendientesDePago($arr[$keys[4]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);

		if ($this->isColumnModified(PeriodoporprestadorservicioPeer::PPS_PRE_ID)) $criteria->add(PeriodoporprestadorservicioPeer::PPS_PRE_ID, $this->pps_pre_id);
		if ($this->isColumnModified(PeriodoporprestadorservicioPeer::PPS_SER_ID)) $criteria->add(PeriodoporprestadorservicioPeer::PPS_SER_ID, $this->pps_ser_id);
		if ($this->isColumnModified(PeriodoporprestadorservicioPeer::PPS_ANIO)) $criteria->add(PeriodoporprestadorservicioPeer::PPS_ANIO, $this->pps_anio);
		if ($this->isColumnModified(PeriodoporprestadorservicioPeer::PPS_PRESUPUESTO_APROBADO)) $criteria->add(PeriodoporprestadorservicioPeer::PPS_PRESUPUESTO_APROBADO, $this->pps_presupuesto_aprobado);
		if ($this->isColumnModified(PeriodoporprestadorservicioPeer::PPS_SUSCRIPTORES_PENDIENTES_DE_PAGO)) $criteria->add(PeriodoporprestadorservicioPeer::PPS_SUSCRIPTORES_PENDIENTES_DE_PAGO, $this->pps_suscriptores_pendientes_de_pago);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);

		$criteria->add(PeriodoporprestadorservicioPeer::PPS_PRE_ID, $this->pps_pre_id);
		$criteria->add(PeriodoporprestadorservicioPeer::PPS_SER_ID, $this->pps_ser_id);
		$criteria->add(PeriodoporprestadorservicioPeer::PPS_ANIO, $this->pps_anio);

		return $criteria;
	}

	/**
	 * Returns the composite primary key for this object.
	 * The array elements will be in same order as specified in XML.
	 * @return     array
	 */
	public function getPrimaryKey()
	{
		$pks = array();

		$pks[0] = $this->getPpsPreId();

		$pks[1] = $this->getPpsSerId();

		$pks[2] = $this->getPpsAnio();

		return $pks;
	}

	/**
	 * Set the [composite] primary key.
	 *
	 * @param      array $keys The elements of the composite key (order must match the order in XML file).
	 * @return     void
	 */
	public function setPrimaryKey($keys)
	{

		$this->setPpsPreId($keys[0]);

		$this->setPpsSerId($keys[1]);

		$this->setPpsAnio($keys[2]);

	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Periodoporprestadorservicio (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setPpsPreId($this->pps_pre_id);

		$copyObj->setPpsSerId($this->pps_ser_id);

		$copyObj->setPpsAnio($this->pps_anio);

		$copyObj->setPpsPresupuestoAprobado($this->pps_presupuesto_aprobado);

		$copyObj->setPpsSuscriptoresPendientesDePago($this->pps_suscriptores_pendientes_de_pago);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getAdministrativafinancieras() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addAdministrativafinanciera($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCalidads() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCalidad($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getCormecials() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addCormecial($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getMicrocuencass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addMicrocuencas($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTecnicooperativos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTecnicooperativo($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Periodoporprestadorservicio Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     PeriodoporprestadorservicioPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new PeriodoporprestadorservicioPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Prestador object.
	 *
	 * @param      Prestador $v
	 * @return     Periodoporprestadorservicio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setPrestador(Prestador $v = null)
	{
		if ($v === null) {
			$this->setPpsPreId(NULL);
		} else {
			$this->setPpsPreId($v->getPreId());
		}

		$this->aPrestador = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Prestador object, it will not be re-added.
		if ($v !== null) {
			$v->addPeriodoporprestadorservicio($this);
		}

		return $this;
	}


	/**
	 * Get the associated Prestador object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Prestador The associated Prestador object.
	 * @throws     PropelException
	 */
	public function getPrestador(PropelPDO $con = null)
	{
		if ($this->aPrestador === null && ($this->pps_pre_id !== null)) {
			$this->aPrestador = PrestadorPeer::retrieveByPk($this->pps_pre_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aPrestador->addPeriodoporprestadorservicios($this);
			 */
		}
		return $this->aPrestador;
	}

	/**
	 * Declares an association between this object and a Servicio object.
	 *
	 * @param      Servicio $v
	 * @return     Periodoporprestadorservicio The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setServicio(Servicio $v = null)
	{
		if ($v === null) {
			$this->setPpsSerId(NULL);
		} else {
			$this->setPpsSerId($v->getSerId());
		}

		$this->aServicio = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Servicio object, it will not be re-added.
		if ($v !== null) {
			$v->addPeriodoporprestadorservicio($this);
		}

		return $this;
	}


	/**
	 * Get the associated Servicio object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Servicio The associated Servicio object.
	 * @throws     PropelException
	 */
	public function getServicio(PropelPDO $con = null)
	{
		if ($this->aServicio === null && ($this->pps_ser_id !== null)) {
			$this->aServicio = ServicioPeer::retrieveByPk($this->pps_ser_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aServicio->addPeriodoporprestadorservicios($this);
			 */
		}
		return $this->aServicio;
	}

	/**
	 * Clears out the collAdministrativafinancieras collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addAdministrativafinancieras()
	 */
	public function clearAdministrativafinancieras()
	{
		$this->collAdministrativafinancieras = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collAdministrativafinancieras collection (array).
	 *
	 * By default this just sets the collAdministrativafinancieras collection to an empty array (like clearcollAdministrativafinancieras());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initAdministrativafinancieras()
	{
		$this->collAdministrativafinancieras = array();
	}

	/**
	 * Gets an array of Administrativafinanciera objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Periodoporprestadorservicio has previously been saved, it will retrieve
	 * related Administrativafinancieras from storage. If this Periodoporprestadorservicio is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Administrativafinanciera[]
	 * @throws     PropelException
	 */
	public function getAdministrativafinancieras($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collAdministrativafinancieras === null) {
			if ($this->isNew()) {
			   $this->collAdministrativafinancieras = array();
			} else {

				$criteria->add(AdministrativafinancieraPeer::IAF_PPS_PRE_ID, $this->pps_pre_id);

				AdministrativafinancieraPeer::addSelectColumns($criteria);
				$this->collAdministrativafinancieras = AdministrativafinancieraPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(AdministrativafinancieraPeer::IAF_PPS_PRE_ID, $this->pps_pre_id);

				AdministrativafinancieraPeer::addSelectColumns($criteria);
				if (!isset($this->lastAdministrativafinancieraCriteria) || !$this->lastAdministrativafinancieraCriteria->equals($criteria)) {
					$this->collAdministrativafinancieras = AdministrativafinancieraPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastAdministrativafinancieraCriteria = $criteria;
		return $this->collAdministrativafinancieras;
	}

	/**
	 * Returns the number of related Administrativafinanciera objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Administrativafinanciera objects.
	 * @throws     PropelException
	 */
	public function countAdministrativafinancieras(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collAdministrativafinancieras === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(AdministrativafinancieraPeer::IAF_PPS_PRE_ID, $this->pps_pre_id);

				$count = AdministrativafinancieraPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(AdministrativafinancieraPeer::IAF_PPS_PRE_ID, $this->pps_pre_id);

				if (!isset($this->lastAdministrativafinancieraCriteria) || !$this->lastAdministrativafinancieraCriteria->equals($criteria)) {
					$count = AdministrativafinancieraPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collAdministrativafinancieras);
				}
			} else {
				$count = count($this->collAdministrativafinancieras);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Administrativafinanciera object to this object
	 * through the Administrativafinanciera foreign key attribute.
	 *
	 * @param      Administrativafinanciera $l Administrativafinanciera
	 * @return     void
	 * @throws     PropelException
	 */
	public function addAdministrativafinanciera(Administrativafinanciera $l)
	{
		if ($this->collAdministrativafinancieras === null) {
			$this->initAdministrativafinancieras();
		}
		if (!in_array($l, $this->collAdministrativafinancieras, true)) { // only add it if the **same** object is not already associated
			array_push($this->collAdministrativafinancieras, $l);
			$l->setPeriodoporprestadorservicio($this);
		}
	}

	/**
	 * Clears out the collCalidads collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCalidads()
	 */
	public function clearCalidads()
	{
		$this->collCalidads = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCalidads collection (array).
	 *
	 * By default this just sets the collCalidads collection to an empty array (like clearcollCalidads());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCalidads()
	{
		$this->collCalidads = array();
	}

	/**
	 * Gets an array of Calidad objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Periodoporprestadorservicio has previously been saved, it will retrieve
	 * related Calidads from storage. If this Periodoporprestadorservicio is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Calidad[]
	 * @throws     PropelException
	 */
	public function getCalidads($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCalidads === null) {
			if ($this->isNew()) {
			   $this->collCalidads = array();
			} else {

				$criteria->add(CalidadPeer::CAL_PPS_PRE_ID, $this->pps_pre_id);

				CalidadPeer::addSelectColumns($criteria);
				$this->collCalidads = CalidadPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CalidadPeer::CAL_PPS_PRE_ID, $this->pps_pre_id);

				CalidadPeer::addSelectColumns($criteria);
				if (!isset($this->lastCalidadCriteria) || !$this->lastCalidadCriteria->equals($criteria)) {
					$this->collCalidads = CalidadPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCalidadCriteria = $criteria;
		return $this->collCalidads;
	}

	/**
	 * Returns the number of related Calidad objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Calidad objects.
	 * @throws     PropelException
	 */
	public function countCalidads(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCalidads === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CalidadPeer::CAL_PPS_PRE_ID, $this->pps_pre_id);

				$count = CalidadPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CalidadPeer::CAL_PPS_PRE_ID, $this->pps_pre_id);

				if (!isset($this->lastCalidadCriteria) || !$this->lastCalidadCriteria->equals($criteria)) {
					$count = CalidadPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCalidads);
				}
			} else {
				$count = count($this->collCalidads);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Calidad object to this object
	 * through the Calidad foreign key attribute.
	 *
	 * @param      Calidad $l Calidad
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCalidad(Calidad $l)
	{
		if ($this->collCalidads === null) {
			$this->initCalidads();
		}
		if (!in_array($l, $this->collCalidads, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCalidads, $l);
			$l->setPeriodoporprestadorservicio($this);
		}
	}

	/**
	 * Clears out the collCormecials collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addCormecials()
	 */
	public function clearCormecials()
	{
		$this->collCormecials = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collCormecials collection (array).
	 *
	 * By default this just sets the collCormecials collection to an empty array (like clearcollCormecials());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initCormecials()
	{
		$this->collCormecials = array();
	}

	/**
	 * Gets an array of Cormecial objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Periodoporprestadorservicio has previously been saved, it will retrieve
	 * related Cormecials from storage. If this Periodoporprestadorservicio is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Cormecial[]
	 * @throws     PropelException
	 */
	public function getCormecials($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collCormecials === null) {
			if ($this->isNew()) {
			   $this->collCormecials = array();
			} else {

				$criteria->add(CormecialPeer::COM_PPS_PRE_ID, $this->pps_pre_id);

				CormecialPeer::addSelectColumns($criteria);
				$this->collCormecials = CormecialPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(CormecialPeer::COM_PPS_PRE_ID, $this->pps_pre_id);

				CormecialPeer::addSelectColumns($criteria);
				if (!isset($this->lastCormecialCriteria) || !$this->lastCormecialCriteria->equals($criteria)) {
					$this->collCormecials = CormecialPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastCormecialCriteria = $criteria;
		return $this->collCormecials;
	}

	/**
	 * Returns the number of related Cormecial objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Cormecial objects.
	 * @throws     PropelException
	 */
	public function countCormecials(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collCormecials === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(CormecialPeer::COM_PPS_PRE_ID, $this->pps_pre_id);

				$count = CormecialPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(CormecialPeer::COM_PPS_PRE_ID, $this->pps_pre_id);

				if (!isset($this->lastCormecialCriteria) || !$this->lastCormecialCriteria->equals($criteria)) {
					$count = CormecialPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collCormecials);
				}
			} else {
				$count = count($this->collCormecials);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Cormecial object to this object
	 * through the Cormecial foreign key attribute.
	 *
	 * @param      Cormecial $l Cormecial
	 * @return     void
	 * @throws     PropelException
	 */
	public function addCormecial(Cormecial $l)
	{
		if ($this->collCormecials === null) {
			$this->initCormecials();
		}
		if (!in_array($l, $this->collCormecials, true)) { // only add it if the **same** object is not already associated
			array_push($this->collCormecials, $l);
			$l->setPeriodoporprestadorservicio($this);
		}
	}

	/**
	 * Clears out the collMicrocuencass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addMicrocuencass()
	 */
	public function clearMicrocuencass()
	{
		$this->collMicrocuencass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collMicrocuencass collection (array).
	 *
	 * By default this just sets the collMicrocuencass collection to an empty array (like clearcollMicrocuencass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initMicrocuencass()
	{
		$this->collMicrocuencass = array();
	}

	/**
	 * Gets an array of Microcuencas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Periodoporprestadorservicio has previously been saved, it will retrieve
	 * related Microcuencass from storage. If this Periodoporprestadorservicio is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Microcuencas[]
	 * @throws     PropelException
	 */
	public function getMicrocuencass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collMicrocuencass === null) {
			if ($this->isNew()) {
			   $this->collMicrocuencass = array();
			} else {

				$criteria->add(MicrocuencasPeer::MIC_PPS_PRE_ID, $this->pps_pre_id);

				MicrocuencasPeer::addSelectColumns($criteria);
				$this->collMicrocuencass = MicrocuencasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(MicrocuencasPeer::MIC_PPS_PRE_ID, $this->pps_pre_id);

				MicrocuencasPeer::addSelectColumns($criteria);
				if (!isset($this->lastMicrocuencasCriteria) || !$this->lastMicrocuencasCriteria->equals($criteria)) {
					$this->collMicrocuencass = MicrocuencasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastMicrocuencasCriteria = $criteria;
		return $this->collMicrocuencass;
	}

	/**
	 * Returns the number of related Microcuencas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Microcuencas objects.
	 * @throws     PropelException
	 */
	public function countMicrocuencass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collMicrocuencass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(MicrocuencasPeer::MIC_PPS_PRE_ID, $this->pps_pre_id);

				$count = MicrocuencasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(MicrocuencasPeer::MIC_PPS_PRE_ID, $this->pps_pre_id);

				if (!isset($this->lastMicrocuencasCriteria) || !$this->lastMicrocuencasCriteria->equals($criteria)) {
					$count = MicrocuencasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collMicrocuencass);
				}
			} else {
				$count = count($this->collMicrocuencass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Microcuencas object to this object
	 * through the Microcuencas foreign key attribute.
	 *
	 * @param      Microcuencas $l Microcuencas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addMicrocuencas(Microcuencas $l)
	{
		if ($this->collMicrocuencass === null) {
			$this->initMicrocuencass();
		}
		if (!in_array($l, $this->collMicrocuencass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collMicrocuencass, $l);
			$l->setPeriodoporprestadorservicio($this);
		}
	}

	/**
	 * Clears out the collTecnicooperativos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTecnicooperativos()
	 */
	public function clearTecnicooperativos()
	{
		$this->collTecnicooperativos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTecnicooperativos collection (array).
	 *
	 * By default this just sets the collTecnicooperativos collection to an empty array (like clearcollTecnicooperativos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTecnicooperativos()
	{
		$this->collTecnicooperativos = array();
	}

	/**
	 * Gets an array of Tecnicooperativo objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Periodoporprestadorservicio has previously been saved, it will retrieve
	 * related Tecnicooperativos from storage. If this Periodoporprestadorservicio is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tecnicooperativo[]
	 * @throws     PropelException
	 */
	public function getTecnicooperativos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTecnicooperativos === null) {
			if ($this->isNew()) {
			   $this->collTecnicooperativos = array();
			} else {

				$criteria->add(TecnicooperativoPeer::TOP_PPS_PRE_ID, $this->pps_pre_id);

				TecnicooperativoPeer::addSelectColumns($criteria);
				$this->collTecnicooperativos = TecnicooperativoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TecnicooperativoPeer::TOP_PPS_PRE_ID, $this->pps_pre_id);

				TecnicooperativoPeer::addSelectColumns($criteria);
				if (!isset($this->lastTecnicooperativoCriteria) || !$this->lastTecnicooperativoCriteria->equals($criteria)) {
					$this->collTecnicooperativos = TecnicooperativoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTecnicooperativoCriteria = $criteria;
		return $this->collTecnicooperativos;
	}

	/**
	 * Returns the number of related Tecnicooperativo objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tecnicooperativo objects.
	 * @throws     PropelException
	 */
	public function countTecnicooperativos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(PeriodoporprestadorservicioPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTecnicooperativos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TecnicooperativoPeer::TOP_PPS_PRE_ID, $this->pps_pre_id);

				$count = TecnicooperativoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TecnicooperativoPeer::TOP_PPS_PRE_ID, $this->pps_pre_id);

				if (!isset($this->lastTecnicooperativoCriteria) || !$this->lastTecnicooperativoCriteria->equals($criteria)) {
					$count = TecnicooperativoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTecnicooperativos);
				}
			} else {
				$count = count($this->collTecnicooperativos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tecnicooperativo object to this object
	 * through the Tecnicooperativo foreign key attribute.
	 *
	 * @param      Tecnicooperativo $l Tecnicooperativo
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTecnicooperativo(Tecnicooperativo $l)
	{
		if ($this->collTecnicooperativos === null) {
			$this->initTecnicooperativos();
		}
		if (!in_array($l, $this->collTecnicooperativos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTecnicooperativos, $l);
			$l->setPeriodoporprestadorservicio($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collAdministrativafinancieras) {
				foreach ((array) $this->collAdministrativafinancieras as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCalidads) {
				foreach ((array) $this->collCalidads as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collCormecials) {
				foreach ((array) $this->collCormecials as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collMicrocuencass) {
				foreach ((array) $this->collMicrocuencass as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTecnicooperativos) {
				foreach ((array) $this->collTecnicooperativos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collAdministrativafinancieras = null;
		$this->collCalidads = null;
		$this->collCormecials = null;
		$this->collMicrocuencass = null;
		$this->collTecnicooperativos = null;
			$this->aPrestador = null;
			$this->aServicio = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BasePeriodoporprestadorservicio:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BasePeriodoporprestadorservicio::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BasePeriodoporprestadorservicio
