<?php

/**
 * Base class that represents a row from the 'materialcanal' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/27/10 18:48:11
 *
 * @package    lib.model.om
 */
abstract class BaseMaterialcanal extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        MaterialcanalPeer
	 */
	protected static $peer;

	/**
	 * The value for the mca_id field.
	 * @var        int
	 */
	protected $mca_id;

	/**
	 * The value for the mca_nombre field.
	 * @var        string
	 */
	protected $mca_nombre;

	/**
	 * @var        array Tecnicooperativaaduccionimpulsionacueducto[] Collection to store aggregation of Tecnicooperativaaduccionimpulsionacueducto objects.
	 */
	protected $collTecnicooperativaaduccionimpulsionacueductos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTecnicooperativaaduccionimpulsionacueductos.
	 */
	private $lastTecnicooperativaaduccionimpulsionacueductoCriteria = null;

	/**
	 * @var        array Tecnicooperativalineaconduccionaguacrudaacueducto[] Collection to store aggregation of Tecnicooperativalineaconduccionaguacrudaacueducto objects.
	 */
	protected $collTecnicooperativalineaconduccionaguacrudaacueductos;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTecnicooperativalineaconduccionaguacrudaacueductos.
	 */
	private $lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'MaterialcanalPeer';

	/**
	 * Get the [mca_id] column value.
	 * 
	 * @return     int
	 */
	public function getMcaId()
	{
		return $this->mca_id;
	}

	/**
	 * Get the [mca_nombre] column value.
	 * 
	 * @return     string
	 */
	public function getMcaNombre()
	{
		return $this->mca_nombre;
	}

	/**
	 * Set the value of [mca_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Materialcanal The current object (for fluent API support)
	 */
	public function setMcaId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->mca_id !== $v) {
			$this->mca_id = $v;
			$this->modifiedColumns[] = MaterialcanalPeer::MCA_ID;
		}

		return $this;
	} // setMcaId()

	/**
	 * Set the value of [mca_nombre] column.
	 * 
	 * @param      string $v new value
	 * @return     Materialcanal The current object (for fluent API support)
	 */
	public function setMcaNombre($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->mca_nombre !== $v) {
			$this->mca_nombre = $v;
			$this->modifiedColumns[] = MaterialcanalPeer::MCA_NOMBRE;
		}

		return $this;
	} // setMcaNombre()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->mca_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->mca_nombre = ($row[$startcol + 1] !== null) ? (string) $row[$startcol + 1] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 2; // 2 = MaterialcanalPeer::NUM_COLUMNS - MaterialcanalPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Materialcanal object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MaterialcanalPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = MaterialcanalPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->collTecnicooperativaaduccionimpulsionacueductos = null;
			$this->lastTecnicooperativaaduccionimpulsionacueductoCriteria = null;

			$this->collTecnicooperativalineaconduccionaguacrudaacueductos = null;
			$this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MaterialcanalPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseMaterialcanal:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				MaterialcanalPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseMaterialcanal:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(MaterialcanalPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseMaterialcanal:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseMaterialcanal:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				MaterialcanalPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			if ($this->isNew() ) {
				$this->modifiedColumns[] = MaterialcanalPeer::MCA_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = MaterialcanalPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setMcaId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += MaterialcanalPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collTecnicooperativaaduccionimpulsionacueductos !== null) {
				foreach ($this->collTecnicooperativaaduccionimpulsionacueductos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTecnicooperativalineaconduccionaguacrudaacueductos !== null) {
				foreach ($this->collTecnicooperativalineaconduccionaguacrudaacueductos as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			if (($retval = MaterialcanalPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collTecnicooperativaaduccionimpulsionacueductos !== null) {
					foreach ($this->collTecnicooperativaaduccionimpulsionacueductos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTecnicooperativalineaconduccionaguacrudaacueductos !== null) {
					foreach ($this->collTecnicooperativalineaconduccionaguacrudaacueductos as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MaterialcanalPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getMcaId();
				break;
			case 1:
				return $this->getMcaNombre();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = MaterialcanalPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getMcaId(),
			$keys[1] => $this->getMcaNombre(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = MaterialcanalPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setMcaId($value);
				break;
			case 1:
				$this->setMcaNombre($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = MaterialcanalPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setMcaId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setMcaNombre($arr[$keys[1]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);

		if ($this->isColumnModified(MaterialcanalPeer::MCA_ID)) $criteria->add(MaterialcanalPeer::MCA_ID, $this->mca_id);
		if ($this->isColumnModified(MaterialcanalPeer::MCA_NOMBRE)) $criteria->add(MaterialcanalPeer::MCA_NOMBRE, $this->mca_nombre);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);

		$criteria->add(MaterialcanalPeer::MCA_ID, $this->mca_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getMcaId();
	}

	/**
	 * Generic method to set the primary key (mca_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setMcaId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Materialcanal (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setMcaNombre($this->mca_nombre);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getTecnicooperativaaduccionimpulsionacueductos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTecnicooperativaaduccionimpulsionacueducto($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTecnicooperativalineaconduccionaguacrudaacueductos() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTecnicooperativalineaconduccionaguacrudaacueducto($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setMcaId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Materialcanal Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     MaterialcanalPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new MaterialcanalPeer();
		}
		return self::$peer;
	}

	/**
	 * Clears out the collTecnicooperativaaduccionimpulsionacueductos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTecnicooperativaaduccionimpulsionacueductos()
	 */
	public function clearTecnicooperativaaduccionimpulsionacueductos()
	{
		$this->collTecnicooperativaaduccionimpulsionacueductos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTecnicooperativaaduccionimpulsionacueductos collection (array).
	 *
	 * By default this just sets the collTecnicooperativaaduccionimpulsionacueductos collection to an empty array (like clearcollTecnicooperativaaduccionimpulsionacueductos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTecnicooperativaaduccionimpulsionacueductos()
	{
		$this->collTecnicooperativaaduccionimpulsionacueductos = array();
	}

	/**
	 * Gets an array of Tecnicooperativaaduccionimpulsionacueducto objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Materialcanal has previously been saved, it will retrieve
	 * related Tecnicooperativaaduccionimpulsionacueductos from storage. If this Materialcanal is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tecnicooperativaaduccionimpulsionacueducto[]
	 * @throws     PropelException
	 */
	public function getTecnicooperativaaduccionimpulsionacueductos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTecnicooperativaaduccionimpulsionacueductos === null) {
			if ($this->isNew()) {
			   $this->collTecnicooperativaaduccionimpulsionacueductos = array();
			} else {

				$criteria->add(TecnicooperativaaduccionimpulsionacueductoPeer::TOAI_MATERIAL_CANAL_ID, $this->mca_id);

				TecnicooperativaaduccionimpulsionacueductoPeer::addSelectColumns($criteria);
				$this->collTecnicooperativaaduccionimpulsionacueductos = TecnicooperativaaduccionimpulsionacueductoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TecnicooperativaaduccionimpulsionacueductoPeer::TOAI_MATERIAL_CANAL_ID, $this->mca_id);

				TecnicooperativaaduccionimpulsionacueductoPeer::addSelectColumns($criteria);
				if (!isset($this->lastTecnicooperativaaduccionimpulsionacueductoCriteria) || !$this->lastTecnicooperativaaduccionimpulsionacueductoCriteria->equals($criteria)) {
					$this->collTecnicooperativaaduccionimpulsionacueductos = TecnicooperativaaduccionimpulsionacueductoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTecnicooperativaaduccionimpulsionacueductoCriteria = $criteria;
		return $this->collTecnicooperativaaduccionimpulsionacueductos;
	}

	/**
	 * Returns the number of related Tecnicooperativaaduccionimpulsionacueducto objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tecnicooperativaaduccionimpulsionacueducto objects.
	 * @throws     PropelException
	 */
	public function countTecnicooperativaaduccionimpulsionacueductos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTecnicooperativaaduccionimpulsionacueductos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TecnicooperativaaduccionimpulsionacueductoPeer::TOAI_MATERIAL_CANAL_ID, $this->mca_id);

				$count = TecnicooperativaaduccionimpulsionacueductoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TecnicooperativaaduccionimpulsionacueductoPeer::TOAI_MATERIAL_CANAL_ID, $this->mca_id);

				if (!isset($this->lastTecnicooperativaaduccionimpulsionacueductoCriteria) || !$this->lastTecnicooperativaaduccionimpulsionacueductoCriteria->equals($criteria)) {
					$count = TecnicooperativaaduccionimpulsionacueductoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTecnicooperativaaduccionimpulsionacueductos);
				}
			} else {
				$count = count($this->collTecnicooperativaaduccionimpulsionacueductos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tecnicooperativaaduccionimpulsionacueducto object to this object
	 * through the Tecnicooperativaaduccionimpulsionacueducto foreign key attribute.
	 *
	 * @param      Tecnicooperativaaduccionimpulsionacueducto $l Tecnicooperativaaduccionimpulsionacueducto
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTecnicooperativaaduccionimpulsionacueducto(Tecnicooperativaaduccionimpulsionacueducto $l)
	{
		if ($this->collTecnicooperativaaduccionimpulsionacueductos === null) {
			$this->initTecnicooperativaaduccionimpulsionacueductos();
		}
		if (!in_array($l, $this->collTecnicooperativaaduccionimpulsionacueductos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTecnicooperativaaduccionimpulsionacueductos, $l);
			$l->setMaterialcanal($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Materialcanal is new, it will return
	 * an empty collection; or if this Materialcanal has previously
	 * been saved, it will retrieve related Tecnicooperativaaduccionimpulsionacueductos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Materialcanal.
	 */
	public function getTecnicooperativaaduccionimpulsionacueductosJoinTecnicooperativo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTecnicooperativaaduccionimpulsionacueductos === null) {
			if ($this->isNew()) {
				$this->collTecnicooperativaaduccionimpulsionacueductos = array();
			} else {

				$criteria->add(TecnicooperativaaduccionimpulsionacueductoPeer::TOAI_MATERIAL_CANAL_ID, $this->mca_id);

				$this->collTecnicooperativaaduccionimpulsionacueductos = TecnicooperativaaduccionimpulsionacueductoPeer::doSelectJoinTecnicooperativo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TecnicooperativaaduccionimpulsionacueductoPeer::TOAI_MATERIAL_CANAL_ID, $this->mca_id);

			if (!isset($this->lastTecnicooperativaaduccionimpulsionacueductoCriteria) || !$this->lastTecnicooperativaaduccionimpulsionacueductoCriteria->equals($criteria)) {
				$this->collTecnicooperativaaduccionimpulsionacueductos = TecnicooperativaaduccionimpulsionacueductoPeer::doSelectJoinTecnicooperativo($criteria, $con, $join_behavior);
			}
		}
		$this->lastTecnicooperativaaduccionimpulsionacueductoCriteria = $criteria;

		return $this->collTecnicooperativaaduccionimpulsionacueductos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Materialcanal is new, it will return
	 * an empty collection; or if this Materialcanal has previously
	 * been saved, it will retrieve related Tecnicooperativaaduccionimpulsionacueductos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Materialcanal.
	 */
	public function getTecnicooperativaaduccionimpulsionacueductosJoinTipocanal($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTecnicooperativaaduccionimpulsionacueductos === null) {
			if ($this->isNew()) {
				$this->collTecnicooperativaaduccionimpulsionacueductos = array();
			} else {

				$criteria->add(TecnicooperativaaduccionimpulsionacueductoPeer::TOAI_MATERIAL_CANAL_ID, $this->mca_id);

				$this->collTecnicooperativaaduccionimpulsionacueductos = TecnicooperativaaduccionimpulsionacueductoPeer::doSelectJoinTipocanal($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TecnicooperativaaduccionimpulsionacueductoPeer::TOAI_MATERIAL_CANAL_ID, $this->mca_id);

			if (!isset($this->lastTecnicooperativaaduccionimpulsionacueductoCriteria) || !$this->lastTecnicooperativaaduccionimpulsionacueductoCriteria->equals($criteria)) {
				$this->collTecnicooperativaaduccionimpulsionacueductos = TecnicooperativaaduccionimpulsionacueductoPeer::doSelectJoinTipocanal($criteria, $con, $join_behavior);
			}
		}
		$this->lastTecnicooperativaaduccionimpulsionacueductoCriteria = $criteria;

		return $this->collTecnicooperativaaduccionimpulsionacueductos;
	}

	/**
	 * Clears out the collTecnicooperativalineaconduccionaguacrudaacueductos collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTecnicooperativalineaconduccionaguacrudaacueductos()
	 */
	public function clearTecnicooperativalineaconduccionaguacrudaacueductos()
	{
		$this->collTecnicooperativalineaconduccionaguacrudaacueductos = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTecnicooperativalineaconduccionaguacrudaacueductos collection (array).
	 *
	 * By default this just sets the collTecnicooperativalineaconduccionaguacrudaacueductos collection to an empty array (like clearcollTecnicooperativalineaconduccionaguacrudaacueductos());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTecnicooperativalineaconduccionaguacrudaacueductos()
	{
		$this->collTecnicooperativalineaconduccionaguacrudaacueductos = array();
	}

	/**
	 * Gets an array of Tecnicooperativalineaconduccionaguacrudaacueducto objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Materialcanal has previously been saved, it will retrieve
	 * related Tecnicooperativalineaconduccionaguacrudaacueductos from storage. If this Materialcanal is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tecnicooperativalineaconduccionaguacrudaacueducto[]
	 * @throws     PropelException
	 */
	public function getTecnicooperativalineaconduccionaguacrudaacueductos($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTecnicooperativalineaconduccionaguacrudaacueductos === null) {
			if ($this->isNew()) {
			   $this->collTecnicooperativalineaconduccionaguacrudaacueductos = array();
			} else {

				$criteria->add(TecnicooperativalineaconduccionaguacrudaacueductoPeer::TOLC_MATERIAL_CANAL_ID, $this->mca_id);

				TecnicooperativalineaconduccionaguacrudaacueductoPeer::addSelectColumns($criteria);
				$this->collTecnicooperativalineaconduccionaguacrudaacueductos = TecnicooperativalineaconduccionaguacrudaacueductoPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TecnicooperativalineaconduccionaguacrudaacueductoPeer::TOLC_MATERIAL_CANAL_ID, $this->mca_id);

				TecnicooperativalineaconduccionaguacrudaacueductoPeer::addSelectColumns($criteria);
				if (!isset($this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria) || !$this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria->equals($criteria)) {
					$this->collTecnicooperativalineaconduccionaguacrudaacueductos = TecnicooperativalineaconduccionaguacrudaacueductoPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria = $criteria;
		return $this->collTecnicooperativalineaconduccionaguacrudaacueductos;
	}

	/**
	 * Returns the number of related Tecnicooperativalineaconduccionaguacrudaacueducto objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tecnicooperativalineaconduccionaguacrudaacueducto objects.
	 * @throws     PropelException
	 */
	public function countTecnicooperativalineaconduccionaguacrudaacueductos(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTecnicooperativalineaconduccionaguacrudaacueductos === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TecnicooperativalineaconduccionaguacrudaacueductoPeer::TOLC_MATERIAL_CANAL_ID, $this->mca_id);

				$count = TecnicooperativalineaconduccionaguacrudaacueductoPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TecnicooperativalineaconduccionaguacrudaacueductoPeer::TOLC_MATERIAL_CANAL_ID, $this->mca_id);

				if (!isset($this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria) || !$this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria->equals($criteria)) {
					$count = TecnicooperativalineaconduccionaguacrudaacueductoPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTecnicooperativalineaconduccionaguacrudaacueductos);
				}
			} else {
				$count = count($this->collTecnicooperativalineaconduccionaguacrudaacueductos);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tecnicooperativalineaconduccionaguacrudaacueducto object to this object
	 * through the Tecnicooperativalineaconduccionaguacrudaacueducto foreign key attribute.
	 *
	 * @param      Tecnicooperativalineaconduccionaguacrudaacueducto $l Tecnicooperativalineaconduccionaguacrudaacueducto
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTecnicooperativalineaconduccionaguacrudaacueducto(Tecnicooperativalineaconduccionaguacrudaacueducto $l)
	{
		if ($this->collTecnicooperativalineaconduccionaguacrudaacueductos === null) {
			$this->initTecnicooperativalineaconduccionaguacrudaacueductos();
		}
		if (!in_array($l, $this->collTecnicooperativalineaconduccionaguacrudaacueductos, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTecnicooperativalineaconduccionaguacrudaacueductos, $l);
			$l->setMaterialcanal($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Materialcanal is new, it will return
	 * an empty collection; or if this Materialcanal has previously
	 * been saved, it will retrieve related Tecnicooperativalineaconduccionaguacrudaacueductos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Materialcanal.
	 */
	public function getTecnicooperativalineaconduccionaguacrudaacueductosJoinTecnicooperativo($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTecnicooperativalineaconduccionaguacrudaacueductos === null) {
			if ($this->isNew()) {
				$this->collTecnicooperativalineaconduccionaguacrudaacueductos = array();
			} else {

				$criteria->add(TecnicooperativalineaconduccionaguacrudaacueductoPeer::TOLC_MATERIAL_CANAL_ID, $this->mca_id);

				$this->collTecnicooperativalineaconduccionaguacrudaacueductos = TecnicooperativalineaconduccionaguacrudaacueductoPeer::doSelectJoinTecnicooperativo($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TecnicooperativalineaconduccionaguacrudaacueductoPeer::TOLC_MATERIAL_CANAL_ID, $this->mca_id);

			if (!isset($this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria) || !$this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria->equals($criteria)) {
				$this->collTecnicooperativalineaconduccionaguacrudaacueductos = TecnicooperativalineaconduccionaguacrudaacueductoPeer::doSelectJoinTecnicooperativo($criteria, $con, $join_behavior);
			}
		}
		$this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria = $criteria;

		return $this->collTecnicooperativalineaconduccionaguacrudaacueductos;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Materialcanal is new, it will return
	 * an empty collection; or if this Materialcanal has previously
	 * been saved, it will retrieve related Tecnicooperativalineaconduccionaguacrudaacueductos from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Materialcanal.
	 */
	public function getTecnicooperativalineaconduccionaguacrudaacueductosJoinTipocanal($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(MaterialcanalPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTecnicooperativalineaconduccionaguacrudaacueductos === null) {
			if ($this->isNew()) {
				$this->collTecnicooperativalineaconduccionaguacrudaacueductos = array();
			} else {

				$criteria->add(TecnicooperativalineaconduccionaguacrudaacueductoPeer::TOLC_MATERIAL_CANAL_ID, $this->mca_id);

				$this->collTecnicooperativalineaconduccionaguacrudaacueductos = TecnicooperativalineaconduccionaguacrudaacueductoPeer::doSelectJoinTipocanal($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(TecnicooperativalineaconduccionaguacrudaacueductoPeer::TOLC_MATERIAL_CANAL_ID, $this->mca_id);

			if (!isset($this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria) || !$this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria->equals($criteria)) {
				$this->collTecnicooperativalineaconduccionaguacrudaacueductos = TecnicooperativalineaconduccionaguacrudaacueductoPeer::doSelectJoinTipocanal($criteria, $con, $join_behavior);
			}
		}
		$this->lastTecnicooperativalineaconduccionaguacrudaacueductoCriteria = $criteria;

		return $this->collTecnicooperativalineaconduccionaguacrudaacueductos;
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collTecnicooperativaaduccionimpulsionacueductos) {
				foreach ((array) $this->collTecnicooperativaaduccionimpulsionacueductos as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTecnicooperativalineaconduccionaguacrudaacueductos) {
				foreach ((array) $this->collTecnicooperativalineaconduccionaguacrudaacueductos as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collTecnicooperativaaduccionimpulsionacueductos = null;
		$this->collTecnicooperativalineaconduccionaguacrudaacueductos = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseMaterialcanal:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseMaterialcanal::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseMaterialcanal
