<?php

/**
 * Base class that represents a row from the 'fuentes' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
<<<<<<< HEAD
 * 07/29/10 00:06:58
=======
 * 07/28/10 21:52:37
>>>>>>> d566463288c5b8110a13446cf8dcc22996c79238
 *
 * @package    lib.model.om
 */
abstract class BaseFuentes extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        FuentesPeer
	 */
	protected static $peer;

	/**
	 * The value for the fue_id field.
	 * @var        int
	 */
	protected $fue_id;

	/**
	 * The value for the fue_mic_id field.
	 * @var        int
	 */
	protected $fue_mic_id;

	/**
	 * The value for the fue_numero_fuentes field.
	 * @var        int
	 */
	protected $fue_numero_fuentes;

	/**
	 * The value for the fue_numero_fuentes_subterraneas field.
	 * @var        int
	 */
	protected $fue_numero_fuentes_subterraneas;

	/**
	 * The value for the fue_compra_agua_bloque field.
	 * @var        string
	 */
	protected $fue_compra_agua_bloque;

	/**
	 * The value for the fue_metodo_aforo_volumetrico field.
	 * @var        string
	 */
	protected $fue_metodo_aforo_volumetrico;

	/**
	 * The value for the fue_metodo_aforo_micromolinete field.
	 * @var        string
	 */
	protected $fue_metodo_aforo_micromolinete;

	/**
	 * The value for the fue_metodo_aforo_velocidad field.
	 * @var        string
	 */
	protected $fue_metodo_aforo_velocidad;

	/**
	 * The value for the fue_metodo_aforo_otro_cual field.
	 * @var        string
	 */
	protected $fue_metodo_aforo_otro_cual;

	/**
	 * The value for the fue_cumple_permisos field.
	 * @var        string
	 */
	protected $fue_cumple_permisos;

	/**
	 * @var        Microcuencas
	 */
	protected $aMicrocuencas;

	/**
	 * @var        array Fuentessubterraneas[] Collection to store aggregation of Fuentessubterraneas objects.
	 */
	protected $collFuentessubterraneass;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFuentessubterraneass.
	 */
	private $lastFuentessubterraneasCriteria = null;

	/**
	 * @var        array Fuentessuperficiales[] Collection to store aggregation of Fuentessuperficiales objects.
	 */
	protected $collFuentessuperficialess;

	/**
	 * @var        Criteria The criteria used to select the current contents of collFuentessuperficialess.
	 */
	private $lastFuentessuperficialesCriteria = null;

	/**
	 * @var        array Tipofuentesuperficial[] Collection to store aggregation of Tipofuentesuperficial objects.
	 */
	protected $collTipofuentesuperficials;

	/**
	 * @var        Criteria The criteria used to select the current contents of collTipofuentesuperficials.
	 */
	private $lastTipofuentesuperficialCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'FuentesPeer';

	/**
	 * Get the [fue_id] column value.
	 * 
	 * @return     int
	 */
	public function getFueId()
	{
		return $this->fue_id;
	}

	/**
	 * Get the [fue_mic_id] column value.
	 * 
	 * @return     int
	 */
	public function getFueMicId()
	{
		return $this->fue_mic_id;
	}

	/**
	 * Get the [fue_numero_fuentes] column value.
	 * 
	 * @return     int
	 */
	public function getFueNumeroFuentes()
	{
		return $this->fue_numero_fuentes;
	}

	/**
	 * Get the [fue_numero_fuentes_subterraneas] column value.
	 * 
	 * @return     int
	 */
	public function getFueNumeroFuentesSubterraneas()
	{
		return $this->fue_numero_fuentes_subterraneas;
	}

	/**
	 * Get the [fue_compra_agua_bloque] column value.
	 * 
	 * @return     string
	 */
	public function getFueCompraAguaBloque()
	{
		return $this->fue_compra_agua_bloque;
	}

	/**
	 * Get the [fue_metodo_aforo_volumetrico] column value.
	 * 
	 * @return     string
	 */
	public function getFueMetodoAforoVolumetrico()
	{
		return $this->fue_metodo_aforo_volumetrico;
	}

	/**
	 * Get the [fue_metodo_aforo_micromolinete] column value.
	 * 
	 * @return     string
	 */
	public function getFueMetodoAforoMicromolinete()
	{
		return $this->fue_metodo_aforo_micromolinete;
	}

	/**
	 * Get the [fue_metodo_aforo_velocidad] column value.
	 * 
	 * @return     string
	 */
	public function getFueMetodoAforoVelocidad()
	{
		return $this->fue_metodo_aforo_velocidad;
	}

	/**
	 * Get the [fue_metodo_aforo_otro_cual] column value.
	 * 
	 * @return     string
	 */
	public function getFueMetodoAforoOtroCual()
	{
		return $this->fue_metodo_aforo_otro_cual;
	}

	/**
	 * Get the [fue_cumple_permisos] column value.
	 * 
	 * @return     string
	 */
	public function getFueCumplePermisos()
	{
		return $this->fue_cumple_permisos;
	}

	/**
	 * Set the value of [fue_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fue_id !== $v) {
			$this->fue_id = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_ID;
		}

		return $this;
	} // setFueId()

	/**
	 * Set the value of [fue_mic_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueMicId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fue_mic_id !== $v) {
			$this->fue_mic_id = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_MIC_ID;
		}

		if ($this->aMicrocuencas !== null && $this->aMicrocuencas->getMicId() !== $v) {
			$this->aMicrocuencas = null;
		}

		return $this;
	} // setFueMicId()

	/**
	 * Set the value of [fue_numero_fuentes] column.
	 * 
	 * @param      int $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueNumeroFuentes($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fue_numero_fuentes !== $v) {
			$this->fue_numero_fuentes = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_NUMERO_FUENTES;
		}

		return $this;
	} // setFueNumeroFuentes()

	/**
	 * Set the value of [fue_numero_fuentes_subterraneas] column.
	 * 
	 * @param      int $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueNumeroFuentesSubterraneas($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->fue_numero_fuentes_subterraneas !== $v) {
			$this->fue_numero_fuentes_subterraneas = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_NUMERO_FUENTES_SUBTERRANEAS;
		}

		return $this;
	} // setFueNumeroFuentesSubterraneas()

	/**
	 * Set the value of [fue_compra_agua_bloque] column.
	 * 
	 * @param      string $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueCompraAguaBloque($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fue_compra_agua_bloque !== $v) {
			$this->fue_compra_agua_bloque = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_COMPRA_AGUA_BLOQUE;
		}

		return $this;
	} // setFueCompraAguaBloque()

	/**
	 * Set the value of [fue_metodo_aforo_volumetrico] column.
	 * 
	 * @param      string $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueMetodoAforoVolumetrico($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fue_metodo_aforo_volumetrico !== $v) {
			$this->fue_metodo_aforo_volumetrico = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_METODO_AFORO_VOLUMETRICO;
		}

		return $this;
	} // setFueMetodoAforoVolumetrico()

	/**
	 * Set the value of [fue_metodo_aforo_micromolinete] column.
	 * 
	 * @param      string $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueMetodoAforoMicromolinete($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fue_metodo_aforo_micromolinete !== $v) {
			$this->fue_metodo_aforo_micromolinete = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_METODO_AFORO_MICROMOLINETE;
		}

		return $this;
	} // setFueMetodoAforoMicromolinete()

	/**
	 * Set the value of [fue_metodo_aforo_velocidad] column.
	 * 
	 * @param      string $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueMetodoAforoVelocidad($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fue_metodo_aforo_velocidad !== $v) {
			$this->fue_metodo_aforo_velocidad = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_METODO_AFORO_VELOCIDAD;
		}

		return $this;
	} // setFueMetodoAforoVelocidad()

	/**
	 * Set the value of [fue_metodo_aforo_otro_cual] column.
	 * 
	 * @param      string $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueMetodoAforoOtroCual($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fue_metodo_aforo_otro_cual !== $v) {
			$this->fue_metodo_aforo_otro_cual = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_METODO_AFORO_OTRO_CUAL;
		}

		return $this;
	} // setFueMetodoAforoOtroCual()

	/**
	 * Set the value of [fue_cumple_permisos] column.
	 * 
	 * @param      string $v new value
	 * @return     Fuentes The current object (for fluent API support)
	 */
	public function setFueCumplePermisos($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->fue_cumple_permisos !== $v) {
			$this->fue_cumple_permisos = $v;
			$this->modifiedColumns[] = FuentesPeer::FUE_CUMPLE_PERMISOS;
		}

		return $this;
	} // setFueCumplePermisos()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->fue_id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->fue_mic_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->fue_numero_fuentes = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->fue_numero_fuentes_subterraneas = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->fue_compra_agua_bloque = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->fue_metodo_aforo_volumetrico = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->fue_metodo_aforo_micromolinete = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->fue_metodo_aforo_velocidad = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->fue_metodo_aforo_otro_cual = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->fue_cumple_permisos = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 10; // 10 = FuentesPeer::NUM_COLUMNS - FuentesPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Fuentes object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aMicrocuencas !== null && $this->fue_mic_id !== $this->aMicrocuencas->getMicId()) {
			$this->aMicrocuencas = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FuentesPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = FuentesPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aMicrocuencas = null;
			$this->collFuentessubterraneass = null;
			$this->lastFuentessubterraneasCriteria = null;

			$this->collFuentessuperficialess = null;
			$this->lastFuentessuperficialesCriteria = null;

			$this->collTipofuentesuperficials = null;
			$this->lastTipofuentesuperficialCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FuentesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFuentes:delete:pre') as $callable)
			{
			  if (call_user_func($callable, $this, $con))
			  {
			    $con->commit();
			
			    return;
			  }
			}

			if ($ret) {
				FuentesPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFuentes:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			} else {
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(FuentesPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseFuentes:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    $con->commit();
			
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseFuentes:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				FuentesPeer::addInstanceToPool($this);
			} else {
				$affectedRows = 0;
			}
			$con->commit();
			return $affectedRows;
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aMicrocuencas !== null) {
				if ($this->aMicrocuencas->isModified() || $this->aMicrocuencas->isNew()) {
					$affectedRows += $this->aMicrocuencas->save($con);
				}
				$this->setMicrocuencas($this->aMicrocuencas);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = FuentesPeer::FUE_ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = FuentesPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setFueId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += FuentesPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collFuentessubterraneass !== null) {
				foreach ($this->collFuentessubterraneass as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collFuentessuperficialess !== null) {
				foreach ($this->collFuentessuperficialess as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collTipofuentesuperficials !== null) {
				foreach ($this->collTipofuentesuperficials as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aMicrocuencas !== null) {
				if (!$this->aMicrocuencas->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aMicrocuencas->getValidationFailures());
				}
			}


			if (($retval = FuentesPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collFuentessubterraneass !== null) {
					foreach ($this->collFuentessubterraneass as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collFuentessuperficialess !== null) {
					foreach ($this->collFuentessuperficialess as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collTipofuentesuperficials !== null) {
					foreach ($this->collTipofuentesuperficials as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FuentesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getFueId();
				break;
			case 1:
				return $this->getFueMicId();
				break;
			case 2:
				return $this->getFueNumeroFuentes();
				break;
			case 3:
				return $this->getFueNumeroFuentesSubterraneas();
				break;
			case 4:
				return $this->getFueCompraAguaBloque();
				break;
			case 5:
				return $this->getFueMetodoAforoVolumetrico();
				break;
			case 6:
				return $this->getFueMetodoAforoMicromolinete();
				break;
			case 7:
				return $this->getFueMetodoAforoVelocidad();
				break;
			case 8:
				return $this->getFueMetodoAforoOtroCual();
				break;
			case 9:
				return $this->getFueCumplePermisos();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = FuentesPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getFueId(),
			$keys[1] => $this->getFueMicId(),
			$keys[2] => $this->getFueNumeroFuentes(),
			$keys[3] => $this->getFueNumeroFuentesSubterraneas(),
			$keys[4] => $this->getFueCompraAguaBloque(),
			$keys[5] => $this->getFueMetodoAforoVolumetrico(),
			$keys[6] => $this->getFueMetodoAforoMicromolinete(),
			$keys[7] => $this->getFueMetodoAforoVelocidad(),
			$keys[8] => $this->getFueMetodoAforoOtroCual(),
			$keys[9] => $this->getFueCumplePermisos(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = FuentesPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setFueId($value);
				break;
			case 1:
				$this->setFueMicId($value);
				break;
			case 2:
				$this->setFueNumeroFuentes($value);
				break;
			case 3:
				$this->setFueNumeroFuentesSubterraneas($value);
				break;
			case 4:
				$this->setFueCompraAguaBloque($value);
				break;
			case 5:
				$this->setFueMetodoAforoVolumetrico($value);
				break;
			case 6:
				$this->setFueMetodoAforoMicromolinete($value);
				break;
			case 7:
				$this->setFueMetodoAforoVelocidad($value);
				break;
			case 8:
				$this->setFueMetodoAforoOtroCual($value);
				break;
			case 9:
				$this->setFueCumplePermisos($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = FuentesPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setFueId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setFueMicId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setFueNumeroFuentes($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setFueNumeroFuentesSubterraneas($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setFueCompraAguaBloque($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setFueMetodoAforoVolumetrico($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setFueMetodoAforoMicromolinete($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setFueMetodoAforoVelocidad($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setFueMetodoAforoOtroCual($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setFueCumplePermisos($arr[$keys[9]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(FuentesPeer::DATABASE_NAME);

		if ($this->isColumnModified(FuentesPeer::FUE_ID)) $criteria->add(FuentesPeer::FUE_ID, $this->fue_id);
		if ($this->isColumnModified(FuentesPeer::FUE_MIC_ID)) $criteria->add(FuentesPeer::FUE_MIC_ID, $this->fue_mic_id);
		if ($this->isColumnModified(FuentesPeer::FUE_NUMERO_FUENTES)) $criteria->add(FuentesPeer::FUE_NUMERO_FUENTES, $this->fue_numero_fuentes);
		if ($this->isColumnModified(FuentesPeer::FUE_NUMERO_FUENTES_SUBTERRANEAS)) $criteria->add(FuentesPeer::FUE_NUMERO_FUENTES_SUBTERRANEAS, $this->fue_numero_fuentes_subterraneas);
		if ($this->isColumnModified(FuentesPeer::FUE_COMPRA_AGUA_BLOQUE)) $criteria->add(FuentesPeer::FUE_COMPRA_AGUA_BLOQUE, $this->fue_compra_agua_bloque);
		if ($this->isColumnModified(FuentesPeer::FUE_METODO_AFORO_VOLUMETRICO)) $criteria->add(FuentesPeer::FUE_METODO_AFORO_VOLUMETRICO, $this->fue_metodo_aforo_volumetrico);
		if ($this->isColumnModified(FuentesPeer::FUE_METODO_AFORO_MICROMOLINETE)) $criteria->add(FuentesPeer::FUE_METODO_AFORO_MICROMOLINETE, $this->fue_metodo_aforo_micromolinete);
		if ($this->isColumnModified(FuentesPeer::FUE_METODO_AFORO_VELOCIDAD)) $criteria->add(FuentesPeer::FUE_METODO_AFORO_VELOCIDAD, $this->fue_metodo_aforo_velocidad);
		if ($this->isColumnModified(FuentesPeer::FUE_METODO_AFORO_OTRO_CUAL)) $criteria->add(FuentesPeer::FUE_METODO_AFORO_OTRO_CUAL, $this->fue_metodo_aforo_otro_cual);
		if ($this->isColumnModified(FuentesPeer::FUE_CUMPLE_PERMISOS)) $criteria->add(FuentesPeer::FUE_CUMPLE_PERMISOS, $this->fue_cumple_permisos);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(FuentesPeer::DATABASE_NAME);

		$criteria->add(FuentesPeer::FUE_ID, $this->fue_id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getFueId();
	}

	/**
	 * Generic method to set the primary key (fue_id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setFueId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Fuentes (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setFueMicId($this->fue_mic_id);

		$copyObj->setFueNumeroFuentes($this->fue_numero_fuentes);

		$copyObj->setFueNumeroFuentesSubterraneas($this->fue_numero_fuentes_subterraneas);

		$copyObj->setFueCompraAguaBloque($this->fue_compra_agua_bloque);

		$copyObj->setFueMetodoAforoVolumetrico($this->fue_metodo_aforo_volumetrico);

		$copyObj->setFueMetodoAforoMicromolinete($this->fue_metodo_aforo_micromolinete);

		$copyObj->setFueMetodoAforoVelocidad($this->fue_metodo_aforo_velocidad);

		$copyObj->setFueMetodoAforoOtroCual($this->fue_metodo_aforo_otro_cual);

		$copyObj->setFueCumplePermisos($this->fue_cumple_permisos);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getFuentessubterraneass() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFuentessubterraneas($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getFuentessuperficialess() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addFuentessuperficiales($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getTipofuentesuperficials() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addTipofuentesuperficial($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setFueId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Fuentes Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     FuentesPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new FuentesPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Microcuencas object.
	 *
	 * @param      Microcuencas $v
	 * @return     Fuentes The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setMicrocuencas(Microcuencas $v = null)
	{
		if ($v === null) {
			$this->setFueMicId(NULL);
		} else {
			$this->setFueMicId($v->getMicId());
		}

		$this->aMicrocuencas = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Microcuencas object, it will not be re-added.
		if ($v !== null) {
			$v->addFuentes($this);
		}

		return $this;
	}


	/**
	 * Get the associated Microcuencas object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Microcuencas The associated Microcuencas object.
	 * @throws     PropelException
	 */
	public function getMicrocuencas(PropelPDO $con = null)
	{
		if ($this->aMicrocuencas === null && ($this->fue_mic_id !== null)) {
			$this->aMicrocuencas = MicrocuencasPeer::retrieveByPk($this->fue_mic_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aMicrocuencas->addFuentess($this);
			 */
		}
		return $this->aMicrocuencas;
	}

	/**
	 * Clears out the collFuentessubterraneass collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFuentessubterraneass()
	 */
	public function clearFuentessubterraneass()
	{
		$this->collFuentessubterraneass = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFuentessubterraneass collection (array).
	 *
	 * By default this just sets the collFuentessubterraneass collection to an empty array (like clearcollFuentessubterraneass());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFuentessubterraneass()
	{
		$this->collFuentessubterraneass = array();
	}

	/**
	 * Gets an array of Fuentessubterraneas objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Fuentes has previously been saved, it will retrieve
	 * related Fuentessubterraneass from storage. If this Fuentes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Fuentessubterraneas[]
	 * @throws     PropelException
	 */
	public function getFuentessubterraneass($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FuentesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFuentessubterraneass === null) {
			if ($this->isNew()) {
			   $this->collFuentessubterraneass = array();
			} else {

				$criteria->add(FuentessubterraneasPeer::FSU_FUE_ID, $this->fue_id);

				FuentessubterraneasPeer::addSelectColumns($criteria);
				$this->collFuentessubterraneass = FuentessubterraneasPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FuentessubterraneasPeer::FSU_FUE_ID, $this->fue_id);

				FuentessubterraneasPeer::addSelectColumns($criteria);
				if (!isset($this->lastFuentessubterraneasCriteria) || !$this->lastFuentessubterraneasCriteria->equals($criteria)) {
					$this->collFuentessubterraneass = FuentessubterraneasPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFuentessubterraneasCriteria = $criteria;
		return $this->collFuentessubterraneass;
	}

	/**
	 * Returns the number of related Fuentessubterraneas objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Fuentessubterraneas objects.
	 * @throws     PropelException
	 */
	public function countFuentessubterraneass(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FuentesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFuentessubterraneass === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FuentessubterraneasPeer::FSU_FUE_ID, $this->fue_id);

				$count = FuentessubterraneasPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FuentessubterraneasPeer::FSU_FUE_ID, $this->fue_id);

				if (!isset($this->lastFuentessubterraneasCriteria) || !$this->lastFuentessubterraneasCriteria->equals($criteria)) {
					$count = FuentessubterraneasPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collFuentessubterraneass);
				}
			} else {
				$count = count($this->collFuentessubterraneass);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Fuentessubterraneas object to this object
	 * through the Fuentessubterraneas foreign key attribute.
	 *
	 * @param      Fuentessubterraneas $l Fuentessubterraneas
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFuentessubterraneas(Fuentessubterraneas $l)
	{
		if ($this->collFuentessubterraneass === null) {
			$this->initFuentessubterraneass();
		}
		if (!in_array($l, $this->collFuentessubterraneass, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFuentessubterraneass, $l);
			$l->setFuentes($this);
		}
	}

	/**
	 * Clears out the collFuentessuperficialess collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addFuentessuperficialess()
	 */
	public function clearFuentessuperficialess()
	{
		$this->collFuentessuperficialess = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collFuentessuperficialess collection (array).
	 *
	 * By default this just sets the collFuentessuperficialess collection to an empty array (like clearcollFuentessuperficialess());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initFuentessuperficialess()
	{
		$this->collFuentessuperficialess = array();
	}

	/**
	 * Gets an array of Fuentessuperficiales objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Fuentes has previously been saved, it will retrieve
	 * related Fuentessuperficialess from storage. If this Fuentes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Fuentessuperficiales[]
	 * @throws     PropelException
	 */
	public function getFuentessuperficialess($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FuentesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collFuentessuperficialess === null) {
			if ($this->isNew()) {
			   $this->collFuentessuperficialess = array();
			} else {

				$criteria->add(FuentessuperficialesPeer::FSP_FUE_ID, $this->fue_id);

				FuentessuperficialesPeer::addSelectColumns($criteria);
				$this->collFuentessuperficialess = FuentessuperficialesPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(FuentessuperficialesPeer::FSP_FUE_ID, $this->fue_id);

				FuentessuperficialesPeer::addSelectColumns($criteria);
				if (!isset($this->lastFuentessuperficialesCriteria) || !$this->lastFuentessuperficialesCriteria->equals($criteria)) {
					$this->collFuentessuperficialess = FuentessuperficialesPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastFuentessuperficialesCriteria = $criteria;
		return $this->collFuentessuperficialess;
	}

	/**
	 * Returns the number of related Fuentessuperficiales objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Fuentessuperficiales objects.
	 * @throws     PropelException
	 */
	public function countFuentessuperficialess(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FuentesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collFuentessuperficialess === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(FuentessuperficialesPeer::FSP_FUE_ID, $this->fue_id);

				$count = FuentessuperficialesPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(FuentessuperficialesPeer::FSP_FUE_ID, $this->fue_id);

				if (!isset($this->lastFuentessuperficialesCriteria) || !$this->lastFuentessuperficialesCriteria->equals($criteria)) {
					$count = FuentessuperficialesPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collFuentessuperficialess);
				}
			} else {
				$count = count($this->collFuentessuperficialess);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Fuentessuperficiales object to this object
	 * through the Fuentessuperficiales foreign key attribute.
	 *
	 * @param      Fuentessuperficiales $l Fuentessuperficiales
	 * @return     void
	 * @throws     PropelException
	 */
	public function addFuentessuperficiales(Fuentessuperficiales $l)
	{
		if ($this->collFuentessuperficialess === null) {
			$this->initFuentessuperficialess();
		}
		if (!in_array($l, $this->collFuentessuperficialess, true)) { // only add it if the **same** object is not already associated
			array_push($this->collFuentessuperficialess, $l);
			$l->setFuentes($this);
		}
	}

	/**
	 * Clears out the collTipofuentesuperficials collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addTipofuentesuperficials()
	 */
	public function clearTipofuentesuperficials()
	{
		$this->collTipofuentesuperficials = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collTipofuentesuperficials collection (array).
	 *
	 * By default this just sets the collTipofuentesuperficials collection to an empty array (like clearcollTipofuentesuperficials());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initTipofuentesuperficials()
	{
		$this->collTipofuentesuperficials = array();
	}

	/**
	 * Gets an array of Tipofuentesuperficial objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Fuentes has previously been saved, it will retrieve
	 * related Tipofuentesuperficials from storage. If this Fuentes is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Tipofuentesuperficial[]
	 * @throws     PropelException
	 */
	public function getTipofuentesuperficials($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FuentesPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collTipofuentesuperficials === null) {
			if ($this->isNew()) {
			   $this->collTipofuentesuperficials = array();
			} else {

				$criteria->add(TipofuentesuperficialPeer::TFU_FUE_ID, $this->fue_id);

				TipofuentesuperficialPeer::addSelectColumns($criteria);
				$this->collTipofuentesuperficials = TipofuentesuperficialPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(TipofuentesuperficialPeer::TFU_FUE_ID, $this->fue_id);

				TipofuentesuperficialPeer::addSelectColumns($criteria);
				if (!isset($this->lastTipofuentesuperficialCriteria) || !$this->lastTipofuentesuperficialCriteria->equals($criteria)) {
					$this->collTipofuentesuperficials = TipofuentesuperficialPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastTipofuentesuperficialCriteria = $criteria;
		return $this->collTipofuentesuperficials;
	}

	/**
	 * Returns the number of related Tipofuentesuperficial objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Tipofuentesuperficial objects.
	 * @throws     PropelException
	 */
	public function countTipofuentesuperficials(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(FuentesPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collTipofuentesuperficials === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(TipofuentesuperficialPeer::TFU_FUE_ID, $this->fue_id);

				$count = TipofuentesuperficialPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(TipofuentesuperficialPeer::TFU_FUE_ID, $this->fue_id);

				if (!isset($this->lastTipofuentesuperficialCriteria) || !$this->lastTipofuentesuperficialCriteria->equals($criteria)) {
					$count = TipofuentesuperficialPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collTipofuentesuperficials);
				}
			} else {
				$count = count($this->collTipofuentesuperficials);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Tipofuentesuperficial object to this object
	 * through the Tipofuentesuperficial foreign key attribute.
	 *
	 * @param      Tipofuentesuperficial $l Tipofuentesuperficial
	 * @return     void
	 * @throws     PropelException
	 */
	public function addTipofuentesuperficial(Tipofuentesuperficial $l)
	{
		if ($this->collTipofuentesuperficials === null) {
			$this->initTipofuentesuperficials();
		}
		if (!in_array($l, $this->collTipofuentesuperficials, true)) { // only add it if the **same** object is not already associated
			array_push($this->collTipofuentesuperficials, $l);
			$l->setFuentes($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collFuentessubterraneass) {
				foreach ((array) $this->collFuentessubterraneass as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collFuentessuperficialess) {
				foreach ((array) $this->collFuentessuperficialess as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collTipofuentesuperficials) {
				foreach ((array) $this->collTipofuentesuperficials as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collFuentessubterraneass = null;
		$this->collFuentessuperficialess = null;
		$this->collTipofuentesuperficials = null;
			$this->aMicrocuencas = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseFuentes:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseFuentes::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseFuentes
