<?php


/**
 * Skeleton subclass for representing a row from the 'parametroxfrecuencia' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/17/10 19:39:17
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Parametroxfrecuencia extends BaseParametroxfrecuencia {

} // Parametroxfrecuencia
