<?php


/**
 * Skeleton subclass for performing query and update operations on the 'periodoporprestadorservicio' table.
 *
 *
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/30/10 12:26:11
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PeriodoporprestadorservicioPeer extends BasePeriodoporprestadorservicioPeer {
	public static function consultarPeriodoPorPrestadorServicio($pps_periodo, $pps_pre_id, $pps_ser_id) {
		$criteria = new Criteria();
		$criteria->add(PeriodoporprestadorservicioPeer::PPS_PERIODO, $pps_periodo);
		$criteria->add(PeriodoporprestadorservicioPeer::PPS_PRE_ID, $pps_pre_id);
		$criteria->add(PeriodoporprestadorservicioPeer::PPS_SER_ID, $pps_ser_id);
		$periodoPorPrestadorServicio = PeriodoporprestadorservicioPeer::doSelectOne($criteria);

		if(!$periodoPorPrestadorServicio) {
			$periodoPorPrestadorServicio = new Periodoporprestadorservicio();
			$periodoPorPrestadorServicio->setPpsPeriodo($pps_periodo);
			$periodoPorPrestadorServicio->setPpsPreId($pps_pre_id);
			$periodoPorPrestadorServicio->setPpsSerId($pps_ser_id);
			$periodoPorPrestadorServicio->save();
		}

		return $periodoPorPrestadorServicio;
	}
} // PeriodoporprestadorservicioPeer
