<?php


/**
 * Skeleton subclass for representing a row from the 'resultadosxpunto' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * 07/30/10 12:26:12
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Resultadosxpunto extends BaseResultadosxpunto {

} // Resultadosxpunto
