asignarTooltip('toa_gravedad_sin_tratamiento', 'Gravedad sin tratamiento');
asignarTooltip('toa_bombeo_sin_tratamiento', 'Bombeo sin tratamiento');
asignarTooltip('toa_gravedad_con_tratamiento', 'Gravedad con tratamiento');
asignarTooltip('toa_bombeo_con_tratamiento', 'Bombeo con tratamiento');
asignarTooltip('toa_gravedad_bombeo_sin_tratamiento', 'Gravedad y bombeo sin tratamiento');
asignarTooltip('toa_gravedad_bombeo_con_tratamiento', 'Gravedad y bombeo con tratamiento');
asignarTooltip('toa_gravedad_sin_tratamiento_bombeo_con_tratamiento', 'Gravedad sin tratamiento y bombeo con tratamiento');
asignarTooltip('toa_gravedad_con_tratamiento_bombeo_sin_tratamiento', 'Gravedad con tratamiento y bombeo sin tratamiento');
asignarTooltip('toa_cantidad_agua_distribuida_por_ano', 'Cantidad de agua distribuida por el sistema en el año en (M<sup>3</sup>)');
asignarTooltip('toa_solucion_acarreo', 'Acarreo');
asignarTooltip('toa_solucion_acarreo_viviendas', 'Número de viviendas');
asignarTooltip('toa_solucion_nacimiento', 'Nacimiento');
asignarTooltip('toa_solucion_nacimiento_viviendas', 'Número de viviendas');
asignarTooltip('toa_solucion_aljibe', 'Aljibe');
asignarTooltip('toa_solucion_aljibe_viviendas', 'Número de viviendas');
asignarTooltip('toa_solucion_agua_lluvia', 'Agua lluvia');
asignarTooltip('toa_solucion_agua_lluvia_viviendas', 'Número de viviendas');
asignarTooltip('toa_solucion_otro', 'Otra');
asignarTooltip('toa_solucion_otro_cual', '¿Cual?');
asignarTooltip('toa_solucion_otro_viviendas', 'Número de viviendas');
