asignarTooltip('tolc_canal_abierto', 'Canal abierto');
asignarTooltip('tolc_canal_abierto_tierra_longitud', 'En tierra -> Longitud(m)');
asignarTooltip('tolc_canal_abierto_tierra_edad', 'En tierra -> Edad(años)');
asignarTooltip('tolc_canal_abierto_concreto_longitud', 'En concreto -> Longitud(m)');
asignarTooltip('tolc_canal_abierto_concreto_edad', 'En concreto -> Edad(años)');
asignarTooltip('tolc_canal_abierto_mamposteria_longitud', 'En mamposteria -> Longitud(m)');
asignarTooltip('tolc_canal_abierto_mamposteria_edad', 'En mamposteria -> Edad(años)');
asignarTooltip('tolc_canal_cubierto', 'Canal cubierto');
asignarTooltip('tolc_canal_cubierto_tierra_longitud', 'En tierra -> Longitud');
asignarTooltip('tolc_canal_cubierto_tierra_edad', 'En tierra -> Edad(años)');
asignarTooltip('tolc_canal_cubierto_concreto_longitud', 'En concreto -> Longitud(m)');
asignarTooltip('tolc_canal_cubierto_concreto_edad', 'En concreto -> Edad(años)');
asignarTooltip('tolc_canal_cubierto_mamposteria_longitud', 'En mamposteria -> Longitud(m)');
asignarTooltip('tolc_canal_cubierto_mamposteria_edad', 'En mamposteria -> Edad(años)');

asignarTooltip('tolc_tuberia', 'Tuberia');
asignarTooltip('tolc_tuberia_asbesto_cemento_longitud', 'En asbesto - cemento -> Longitud(m)');
asignarTooltip('tolc_tuberia_asbesto_cemento_diametro', 'En asbesto - cemento -> Diámetro');
asignarTooltip('tolc_tuberia_asbesto_cemento_edad', 'En asbesto - cemento -> Edad(años)');
asignarTooltip('tolc_tuberia_hierro_ductil_longitud', 'En hierro ductil -> Longitud(m)');
asignarTooltip('tolc_tuberia_hierro_ductil_diametro', 'En hierro ductil -> Diámetro');
asignarTooltip('tolc_tuberia_hierro_ductil_edad', 'En hierro ductil -> Edad(años)');
asignarTooltip('tolc_tuberia_concreto_longitud', 'En concreto -> Longitud(m)');
asignarTooltip('tolc_tuberia_concreto_diametro', 'En concreto -> Diámetro');
asignarTooltip('tolc_tuberia_concreto_edad', 'En concreto -> Edad(años)');
asignarTooltip('tolc_tuberia_pvc_longitud', 'PVC -> Longitud(m)');
asignarTooltip('tolc_tuberia_pvc_diametro', 'PVC -> Diámetro');
asignarTooltip('tolc_tuberia_pvc_edad', 'PVC -> Edad(años)');
asignarTooltip('tolc_manguera', 'Manguera');
asignarTooltip('tolc_manguera_polietileno_hd_longitud', 'Polietileno HD -> Longitud(m)');
asignarTooltip('tolc_manguera_polietileno_hd_diametro', 'Polietileno HD -> Diámetro');
asignarTooltip('tolc_manguera_polietileno_hd_edad', 'Polietileno HD -> Edad(años)');
asignarTooltip('tolc_manguera_polietileno_ld_longitud', 'Polietileno LD -> Longitud(m)');
asignarTooltip('tolc_manguera_polietileno_ld_diametro', 'Polietileno LD -> Diámetro');
asignarTooltip('tolc_manguera_polietileno_ld_edad', 'Polietileno LD -> Edad(años)');
asignarTooltip('tolc_manguera_otro_nombre', 'Nombre del otro material');
asignarTooltip('tolc_manguera_otro_longitud', 'Otro -> Longitud(m)');
asignarTooltip('tolc_manguera_otro_diametro', 'Otro -> Diámetro');
asignarTooltip('tolc_manguera_otro_edad', 'Otro -> Edad(años)');

asignarTooltip('tolc_otro', 'Otro canal');
asignarTooltip('tolc_otro_tipo_nombre', 'Nombre del canal');
asignarTooltip('tolc_otro_otro1_longitud', 'Material 1 -> Longitud(m)');
asignarTooltip('tolc_otro_otro1_diametro', 'Material 1 -> Diámetro');
asignarTooltip('tolc_otro_otro1_edad', 'Material 1 -> Edad(años)');
asignarTooltip('tolc_otro_otro1_nombre', 'Material 1 -> Nombre');
asignarTooltip('tolc_otro_otro2_longitud', 'Material 2 -> Longitud(m)');
asignarTooltip('tolc_otro_otro2_diametro', 'Material 2 -> Diámetro');
asignarTooltip('tolc_otro_otro2_edad', 'Material 2 -> Edad(años)');
asignarTooltip('tolc_otro_otro2_nombre', 'Material 2 -> Nombre');
asignarTooltip('tolc_otro_otro3_longitud', 'Material 3 -> Longitud(m)');
asignarTooltip('tolc_otro_otro3_diametro', 'Material 3 -> Diámetro');
asignarTooltip('tolc_otro_otro3_edad', 'Material 3 -> Edad(años)');
asignarTooltip('tolc_otro_otro3_nombre', 'Material 3 -> Nombre');
