var ayuda_acu_fac_frecuencia_del_servicio='Factura el servicio?, seleccion si o no';
var ayuda_acu_fac_frecuenc_facturacion='Con que frecuencia factura el servicio, escoja entre las opciones, si no esta escoja otra y escriba cual';
var ayuda_acu_fac_frecuenc_fac_justificacion='Escriba con que frecuencia factura';
var ayuda_acu_fac_num_fac_exp_ultimo_periodo='Escriba el n&uacute;mero de facturas expedidas en el &uacute;ltimo periodo de facturaci&oacute;n';
var ayuda_acu_fac_sist_fac_utilizado='Como es el sistema de facturaci&oacute;n que utiliza, escoja entre las opciones';
var ayuda_acu_fac_frecuencia_fac_justifica='Escriba que sistema de facturacion utiliza';
var ayuda_acu_fac_morosidad_promedio='Morosidad promedio de los ultimos 3 periodos de pago, en porcentaje';
var ayuda_acu_fac_vol_agua_fac_en_el_anio_acu='Volumen de agua facturado en el a&ntilde;o, escriba un n&uacute;mero';
var ayuda_acu_fac_vol_agua_suministrado_anio_acu='Volumen de agua suministrado en el a&ntilde;o, escriba un n&uacute;mero';
